FROM node:lts-alpine3.20

# Set environment
ENV NODE_ENV=production
WORKDIR /app


# Copy only the dependency manifests first (for caching)
COPY package.json package-lock.json tsconfig.json ./
RUN npm install -g @swc/cli @swc/core

# Install ALL deps (including dev, because build needs them)
RUN npm ci

# Copy source code
COPY src ./src
COPY .swcrc tsconfig.json .env ./

# Build the app
RUN npm run build



EXPOSE 3000

CMD ["node", "dist/src/server.js"]
